"""initial schema

Revision ID: 0a4a5d8c78a4
Revises: 
Create Date: 2026-04-20 10:50:21.128987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4a5d8c78a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colegios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre_colegio', sa.String(length=255), nullable=False),
    sa.Column('rut_sostenedor', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('alumnos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('colegio_id', sa.String(length=36), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('curso', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alumnos_colegio_id'), ['colegio_id'], unique=False)

    op.create_table('permisos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rol_id', sa.String(length=36), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('puede_crear', sa.Boolean(), nullable=True),
    sa.Column('puede_leer', sa.Boolean(), nullable=True),
    sa.Column('puede_editar', sa.Boolean(), nullable=True),
    sa.Column('puede_eliminar', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.create_index('ix_permisos_rol_modulo', ['rol_id', 'modulo'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('colegio_id', sa.String(length=36), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'extraescolar', 'coordinador', name='rolenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_colegio_id'), ['colegio_id'], unique=False)
        batch_op.create_index('ix_usuarios_rut_colegio', ['rut', 'colegio_id'], unique=True)

    op.create_table('talleres',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('colegio_id', sa.String(length=36), nullable=False),
    sa.Column('nombre_taller', sa.String(length=255), nullable=False),
    sa.Column('profesor_id', sa.String(length=36), nullable=False),
    sa.Column('cupos_maximos', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_talleres_colegio_id'), ['colegio_id'], unique=False)

    op.create_table('inscripciones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('colegio_id', sa.String(length=36), nullable=False),
    sa.Column('taller_id', sa.String(length=36), nullable=False),
    sa.Column('alumno_id', sa.String(length=36), nullable=False),
    sa.Column('estado', sa.Enum('inscrito', 'retirado', name='estadoinscripcionenum'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inscripciones_colegio_id'), ['colegio_id'], unique=False)

    op.create_table('sesiones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('colegio_id', sa.String(length=36), nullable=False),
    sa.Column('taller_id', sa.String(length=36), nullable=False),
    sa.Column('fecha_sesion', sa.Date(), nullable=False),
    sa.Column('tematica', sa.String(length=255), nullable=True),
    sa.Column('creado_por', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sesiones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesiones_colegio_id'), ['colegio_id'], unique=False)

    op.create_table('asistencias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('colegio_id', sa.String(length=36), nullable=False),
    sa.Column('sesion_id', sa.String(length=36), nullable=False),
    sa.Column('alumno_id', sa.String(length=36), nullable=False),
    sa.Column('estado_asistencia', sa.Enum('presente', 'ausente', 'justificado', 'atraso', name='estadoasistenciaenum'), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asistencias_colegio_id'), ['colegio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asistencias_colegio_id'))

    op.drop_table('asistencias')
    with op.batch_alter_table('sesiones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesiones_colegio_id'))

    op.drop_table('sesiones')
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inscripciones_colegio_id'))

    op.drop_table('inscripciones')
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_talleres_colegio_id'))

    op.drop_table('talleres')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index('ix_usuarios_rut_colegio')
        batch_op.drop_index(batch_op.f('ix_usuarios_colegio_id'))

    op.drop_table('usuarios')
    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.drop_index('ix_permisos_rol_modulo')

    op.drop_table('permisos')
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alumnos_colegio_id'))

    op.drop_table('alumnos')
    op.drop_table('roles')
    op.drop_table('colegios')
    # ### end Alembic commands ###
