"""make_usuario_colegio_id_nullable

Revision ID: 789ff2e253d3
Revises: b2c3d4e5f6a7
Create Date: 2026-05-06 12:03:41.520644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '789ff2e253d3'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('colegio_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('colegio_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               nullable=False)

    # ### end Alembic commands ###
