"""add reportes_programados table

Revision ID: 8b1cc8f960ec
Revises: 9e0b13294d05
Create Date: 2026-07-02 15:06:38.964676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1cc8f960ec'
down_revision: Union[str, None] = '9e0b13294d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportes_programados',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('colegio_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('frecuencia', sa.Enum('diario', 'semanal', 'mensual', name='frecuenciaenum'), nullable=False),
    sa.Column('destinatarios', sa.JSON(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ultima_ejecucion', sa.String(length=10), nullable=True),
    sa.Column('ultimo_estado', sa.String(length=100), nullable=True),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('creado_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reportes_programados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reportes_programados_colegio_id'), ['colegio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes_programados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reportes_programados_colegio_id'))

    op.drop_table('reportes_programados')
    # ### end Alembic commands ###
