"""add_school_theme_and_logo

Revision ID: 9e0b13294d05
Revises: a1c2e3f4b5d6
Create Date: 2026-06-04 12:53:01.616958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9e0b13294d05'
down_revision: Union[str, None] = 'a1c2e3f4b5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colegios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tema_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.alter_column('dia',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'Lunes'"))
        batch_op.create_index(batch_op.f('ix_talleres_periodo'), ['periodo'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['nombre'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)

    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_talleres_periodo'))
        batch_op.alter_column('dia',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Lunes'"))

    with op.batch_alter_table('colegios', schema=None) as batch_op:
        batch_op.drop_column('logo_url')
        batch_op.drop_column('tema_color')

    # ### end Alembic commands ###
